import { Inter, Carter_One, Castoro } from 'next/font/google';
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/header";
import Hero from "@/components/hero/hero";

// Load fonts
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const carter = Carter_One({ subsets: ['latin'], weight: '400', variable: '--font-carter' });
const castoro = Castoro({ subsets: ['latin'], weight: '400', variable: '--font-castoro' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${carter.variable} ${castoro.variable}`}>
        <Header />
        <Hero />
        {children}
      </body>
    </html>
  );
}
